spring.application.name=proyectominecraft
firebase.project-id=proyecto-weboo
firebase.credentials.path=${GOOGLE_APPLICATION_CREDENTIALS:proyecto-weboo-firebase-adminsdk-fbsvc-ff60dbc800.json}
firebase.web-api-key=AIzaSyCLEfAC0qF7qCAouDSmrQplmyEeQ6y8Am4
admin.emails=${ADMIN_EMAILS:enmanuel.barrera2201@alumnos.ubiobio.cl}
